export const defaultItems = {
  ARTE: [
    "Dirección de artistas",
    "Actores + Serpiente",
    "Escenario extra",
    "Escenografía",
    "Viático Escenografía",
    "Peón de Escenografía",
    "Horas extra personal-Montaje",
    "Riggers",
    "Pista",
    "Peones Pista",
    "Flete",
    "Peones Carga y Descarga",
    "Ignifugado",
    "Depósito",
    "Personal eléctrico armado",
    "VJ",
    "Pantallas",
    "Fx",
    "Presentación",
    "Iluminador",
    "Asistente de Iluminación",
    "Luces Extras",
    "Máquina de Humo",
    "Aduana",
    "Glitter",
    "Peinados",
    "Tattoo",
    "Maquillaje",
    "Pochoclos",
    "Productos de limpieza",
    "Bola Disco",
    "Tintorería",
    "Rider iluminación",
    "Pasacables",
    "Escaleras",
    "Vestuario",
    "Visuales",
    "Máscara de Serpiente",
  ],
  BOOKING: [
    "DJ",
    "Cabina DJ",
    "Armado de Lista",
    "CDJ",
    "CDJ Falsa",
    "Asistentes",
    "Sonidista",
    "Consola Sonido",
    "Agregados sonido",
    "Boletero",
    "Validadores QR",
    "Seguro de accidentes personales",
    "Seguridad",
    "Policías",
    "Paramédicos",
    "Ambulancia",
    "Precintos/Pulseras",
    "Hospedaje",
    "Movilidad",
    "Viáticos",
    "Espacio Públicos",
    "SADAIC",
    "ADICAPIF",
    "Grupo electrógeno",
    "Gasoil Generador",
    "Consumo en venue",
    "Camareras extra",
    "Rider sonido",
    "Conexiones eléctricas",
    "Mesa con consumo",
    "Mesas sin consumo",
    "Guardarropa",
    "Enfermería",
    "Ingreso VIP",
    "Upgrade Entrada",
    "Precio Entrada Efectivo/MP",
    "Vallado",
  ],
  MARKETING: [
    "Creadora de contenido",
    "Filmmaker",
    "Fotografía",
    "Merch",
    "PR",
    "Consumo Influencers",
    "Impresiones y Señalética",
    "Creación Grupo MKT–Acceso",
    "LED puesto Merch",
    "Anabella Manual-especificaciones",
  ],
  "EXTRAS PRODUCCIÓN": [
    "Capacidad y Habilitación",
    "Hora inicio/fin fiesta",
    "Horarios de armado/desarme",
    "Carga/descarga escenografía",
    "Carga/descarga pista",
    "Armado/desarmado pista",
    "Apertura de puertas",
    "Cierre de puertas",
    "Horarios técnicos",
  ],
}

export const checklistMaestro = [
  {
    area: "Producción",
    tareas: "Cronograma, permisos carga, listas staff/acreditaciones, envío de mensajes",
  },
  {
    area: "Booking",
    tareas: "Confirmar DJ·backline·guest list",
  },
  {
    area: "Arte/Técnica",
    tareas: "Confirmar FX, VJ, escenografía, riggers, riders técnicos",
  },
  {
    area: "Marketing",
    tareas: "Confirmar fotógraf@, creador@ contenido, grupo difusión, cartelería",
  },
  {
    area: "Logística",
    tareas: "Camión ida/vuelta, horarios montaje/desarme",
  },
  {
    area: "Seguridad",
    tareas: "Seguridad privada, policía, paramédicos, ambulancia",
  },
  {
    area: "Post-evento",
    tareas: "Desarme, reporte incidencias, cierre económico",
  },
]

export const manualesRol = [
  {
    rol: "Socios",
    descripcion: "Supervisión global, contacto con autoridades, decisiones estratégicas.",
  },
  {
    rol: "Productor",
    descripcion: "Coordina áreas, valida cronograma, resuelve contingencias.",
  },
  {
    rol: "Asistente Producción",
    descripcion: "Recibe proveedores, gestiona puerta/validadores, actualiza checklist en vivo.",
  },
  {
    rol: "Asistentes",
    descripcion: "Control puerta, acompañamiento artistas, monitoreo zonas (baños, VIP).",
  },
  {
    rol: "Validadores/Boleteros",
    descripcion: "Escaneo QR, entrega pulseras, reporte irregularidades, orden de flujo.",
  },
]
